# fly.toml app configuration file generated for ml-zoomcamp-2025-midterm-project on 2025-11-15T09:12:10-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ml-zoomcamp-2025-midterm-project'
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[http_service.concurrency]
  type = "requests"  # Better for Flask than "connections"
  soft_limit = 20    # Start deprioritizing this machine
  hard_limit = 25    # STOP sending traffic (returns 503)

[[http_service.checks]]
  grace_period = "10s"
  interval = "15s"
  method = "GET"
  timeout = "3s"
  path = "/health"

[[vm]]
  memory = "1gb" 
  size = "shared-cpu-1x" 
  cpus = 1
  cpu_kind = "shared"
